apiVersion: cnf.namla.com/v1alpha1
kind: CloudNativeNetworkControllerVpnProfile
metadata:
  name: cnf-vpn-profile-cnf-lan-lan-2-edge-oussama2
  namespace: namla-system
spec:
  nodename: edge-oussama2
  cnf: cnf-lan-lan-2-edge-oussama2
  config:
    controllerId:
      id: controllercnf@namla.cloud
      type: RFC822_ADDR
    controllerIpAddress: 35.247.32.181
    transportNetwork: internet
    mgmtType: SINGLE
    localId:
      id: lan-edge-oussama2@namla.cloud
      type: RFC822_ADDR
    authentication:
      type: psk
      name: controller1-cnf
      key: password
    outGoingCnfs: 
    - cnf-wan-internet-1-edge-oussama2
    - cnf-wan-mpls-1-edge-oussama2
