apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client 
  name: client
spec:
  nodeName: edge-oussama1
  containers:
  - args:
    - busybox
    image: busybox
    name: pod
    command: 
    - "sh"
    - "-c"
    - "while true; do sleep 3600; done"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
