apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client-vpp
  name: client-vpp
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    privileged: true
  volumes:
  - hostPath:
      path: /tmp/memif
      type: ""
    name: memif-sockets
  containers:
  - image: ligato/vpp-base
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done;"]
    name: client-vpp
    resources: {}
    volumeMounts:
    - mountPath: /tmp
      name: memif-sockets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama2
status: {}
