apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: ubuntu:22.04
    name: ubuntu
    command: ["/bin/bash", "-c", "echo Hello from Ubuntu pod; while true; do sleep 3600; done;"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama2
status: {}
