apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client-vpp
  name: client-vpp
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
  - hostPath:
      path: /tmp/memif
      type: ""
    name: memif-sockets
  containers:
  - image: namla/vpp-agent:v1.0-amd64
    name: client-vpp
    resources: {}
    securityContext: 
      privileged: true
    resources:
          limits:
            #memory: "1Gi"  # Example memory limit
            hugepages-2Mi: "1Gi" 
            cpu: "1"       # Example CPU limit
          requests:
            #memory: "1Gi"  # Example memory request
            hugepages-2Mi: "512Mi" 
            cpu: "1"       # Example CPU request
    volumeMounts:
    - mountPath: /tmp
      name: memif-sockets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama2
status: {}
