apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  volumes:
  - hostPath:
      path: /tmp/memif
      type: ""
    name: memif-sockets
  containers:
  - image: ligato/vpp-base:latest
    name: client1
    resources: {}
    volumeMounts:
    - mountPath: /tmp
      name: memif-sockets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama2
status: {}
