apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: client-vpp
  name: client-vpp
spec:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  volumes:
  - hostPath:
      path: /tmp/memif
      type: ""
    name: memif-sockets
  containers:
  - image: ubuntu:22.04
    name: client-vpp
    resources: {}
    securityContext: 
      privileged: true
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done;"]
    #resources:
          #limits:
            #memory: "1Gi"  # Example memory limit
            #hugepages-2Mi: "1Gi" 
            #cpu: "1"       # Example CPU limit
          #requests:
            #memory: "1Gi"  # Example memory request
            #hugepages-2Mi: "1Gi" 
            #cpu: "1"       # Example CPU request
    volumeMounts:
    - mountPath: /tmp
      name: memif-sockets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama2
status: {}
