apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: server
  name: vpp-server
spec:
  volumes:
  - hostPath:
      path: /tmp/memif
      type: ""
    name: memif-sockets
  containers:
  - image: ubuntu:22.04
    command: ["/bin/bash", "-c", "while true; sleep 3600; done;"]
    name: server-vpp
    resources: {}
    volumeMounts:
    - mountPath: /tmp
      name: memif-sockets
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: edge-oussama1
status: {}
