apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  nodeName: edge-oussama1
  containers:
  - image: busybox
    name: busybox
    command: 
    - "sh"
    - "-c"
    - "while true; do sleep 3600; done"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
