apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  nodeName: edge-oussama1
  containers:
  - image: centos8 
    name: centos 
    command:
    - "sh"
    - "-c"
    - "while true; do sleep 3600; done"
  restartPolicy: Always
