apiVersion: v1
kind: Pod
metadata:
  name: client
spec:
  nodeName: edge-oussama1
  containers:
  - image: centos:centos8
    name: centos 
    command:
    - "sh"
    - "-c"
    - "while true; do sleep 3600; done"
    securityContext:
            privileged: true
            capabilities:
              add: ["NET_ADMIN"]
  restartPolicy: Always
